version: "3"
services:
  tippmixoddsinfo_mysql:
    image: mysql:5.7
    ports:
      - "4306:3306"
    env_file:
      - .env 
  tippmixoddsinfo_scraper:
    image: sanyi002/tippmixoddsinfo_scraper:snapshot1.0.0
    environment: 
      - TZ=Europe/Budapest
    build: 
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on: 
      - tippmixoddsinfo_mysql
    volumes: 
      - "./scraper/src:/home/scraper/src"
  tippmixoddsinfo_web:
    image: sanyi002/tippmixoddsinfo_api:beta1.0
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./api/src:/var/www/html"
      - "./api/vendor:/var/www/html/vendor"
