version: "3"
services:
  tippmixoddsinfo_mysql:
    image: mysql:5.7
    ports:
      - "4306:3306"
    env_file:
      - .env 
  tippmixoddsinfo_scraper:
    image: sanyi002/tippmixoddsinfo_scraper:snapshot1.0.0
    build: 
      context: ./scraper
      dockerfile: Dockerfile
    command: tail -F anything
    ports:
      - "9000:9000"
    depends_on: 
      - tippmixoddsinfo_mysql
    volumes: 
      - "./scraper/src:/home/scraper"
